aws_region         = "us-west-2"
environment        = "local-dev"
service_underscore = "auth_service"
service_hyphen     = "auth-service"
dynamodb_table     = "auth"
cognito_client_id  = "1elmeebe63429tcjdvgoedl343"
