aws_region                                    = "us-east-1"
environment                                   = "dev"
lambda_architecture                           = "x86_64"
domain_name                                   = "aws-educate.tw"
docker_host                                   = "npipe:////./pipe/docker_engine"
