aws_region         = "ap-northeast-1"
environment        = "prod"
service_underscore = "api_gateway_custom_domain"
service_hyphen     = "api-gateway-custom-domain"
domain_name        = "awseducate.systems"
