version = 0.1
[default.deploy.parameters]
stack_name = "create-campaign"
resolve_s3 = true
s3_prefix = "create-campaign"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
