from enum import Enum


class ValidationErrorCode(str, Enum):
    """Enumeration of validation error codes."""

    # General validation errors
    VALIDATION_ERROR = "VALIDATION_ERROR"
    VALIDATION_ERRORS = "VALIDATION_ERRORS"

    # Run type errors
    INVALID_RUN_TYPE = "INVALID_RUN_TYPE"

    # Subject and template errors
    MISSING_SUBJECT = "MISSING_SUBJECT"
    MISSING_TEMPLATE_FILE_ID = "MISSING_TEMPLATE_FILE_ID"
    TEMPLATE_RETRIEVAL_ERROR = "TEMPLATE_RETRIEVAL_ERROR"

    # Template variable errors
    MISSING_TEMPLATE_VARIABLES_DIRECT = "MISSING_TEMPLATE_VARIABLES_DIRECT"
    MISSING_TEMPLATE_VARIABLES_SPREADSHEET = "MISSING_TEMPLATE_VARIABLES_SPREADSHEET"

    # Spreadsheet errors
    MISSING_SPREADSHEET_FILE_ID = "MISSING_SPREADSHEET_FILE_ID"
    SPREADSHEET_INFO_ERROR = "SPREADSHEET_INFO_ERROR"
    INVALID_SPREADSHEET_FILE = "INVALID_SPREADSHEET_FILE"
    EMPTY_SPREADSHEET = "EMPTY_SPREADSHEET"
    MISSING_SPREADSHEET_HEADERS = "MISSING_SPREADSHEET_HEADERS"
    INVALID_EMAIL_FORMAT_SPREADSHEET = "INVALID_EMAIL_FORMAT_SPREADSHEET"

    # Recipients errors
    EMPTY_RECIPIENTS_LIST = "EMPTY_RECIPIENTS_LIST"
    INVALID_RECIPIENT_EMAIL_FORMAT = "INVALID_RECIPIENT_EMAIL_FORMAT"

    # Certificate errors
    MISSING_CERTIFICATE_FIELDS_DIRECT = "MISSING_CERTIFICATE_FIELDS_DIRECT"
    MISSING_CERTIFICATE_COLUMNS_SPREADSHEET = "MISSING_CERTIFICATE_COLUMNS_SPREADSHEET"

    # Email format errors
    INVALID_CC_EMAIL_FORMAT = "INVALID_CC_EMAIL_FORMAT"
    INVALID_BCC_EMAIL_FORMAT = "INVALID_BCC_EMAIL_FORMAT"
    INVALID_REPLY_TO_FORMAT = "INVALID_REPLY_TO_FORMAT"

    # Webhook specific errors
    MISSING_RUN_ID_WEBHOOK = "MISSING_RUN_ID_WEBHOOK"
    INVALID_RECIPIENT_SOURCE_WEBHOOK = "INVALID_RECIPIENT_SOURCE_WEBHOOK"
    UNEXPECTED_RUN_ID = "UNEXPECTED_RUN_ID"


class SystemErrorCode(str, Enum):
    """Enumeration of system-level error codes."""

    # External service errors
    EXTERNAL_API_ERROR = "EXTERNAL_API_ERROR"

    # AWS service errors
    SQS_QUEUE_ERROR = "SQS_QUEUE_ERROR"

    # Internal errors
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"