version = 0.1
[default.deploy.parameters]
stack_name = "validate-input"
resolve_s3 = true
s3_prefix = "validate-input"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "AwsRegion=\"us-east-1\""
image_repositories = ["ValidateInputFunction=070576557102.dkr.ecr.us-east-1.amazonaws.com/validateinput0ae3ea30/validateinputfunction28c7d7d1repo"]
