aws_region          = "us-west-2"
environment         = "local-dev"
service_underscore  = "lambda_authorizer"
service_hyphen      = "lambda-authorizer"
lambda_architecture = "arm64"
domain_name         = "awseducate.systems"
