aws_region          = "us-west-1"
environment         = "preview"
service_underscore  = "lambda_authorizer"
service_hyphen      = "lambda-authorizer"
lambda_architecture = "arm64"
domain_name         = "awseducate.systems"
