aws_region          = "ap-northeast-1"
environment         = "prod"
service_underscore  = "lambda_authorizer"
service_hyphen      = "lambda-authorizer"
lambda_architecture = "x86_64"
domain_name         = "awseducate.systems"
