name: Slack Deployment Notification

on:
  workflow_run:
    workflows: ["*"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' ||
      github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Service Name
        id: service-name
        run: |
          WORKFLOW_NAME="${{ github.event.workflow_run.name }}"

          # If this is the Slack notification workflow itself, skip service name extraction
          if [[ $WORKFLOW_NAME == *"Slack Deployment Notification"* ]]; then
            echo "service_name=NOTIFICATION" >> $GITHUB_OUTPUT
            exit 0
          fi

          # For service workflows, extract the name before "Service"
          if [[ $WORKFLOW_NAME =~ ^([A-Za-z]+)\ Service ]]; then
            SERVICE_NAME="${BASH_REMATCH[1]}"
            echo "service_name=${SERVICE_NAME^^}" >> $GITHUB_OUTPUT
          else
            # Fallback: if pattern not found, use UNKNOWN
            echo "service_name=UNKNOWN" >> $GITHUB_OUTPUT
          fi

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ github.event.workflow_run.conclusion }}
          fields: repo,message,commit,author
          custom_payload: |
            {
              "attachments": [{
                "color": "${{ github.event.workflow_run.conclusion == 'success' && 'good' || 'danger' }}",
                "title": "[${{ steps.service-name.outputs.service_name }}] Deployment ${{ github.event.workflow_run.conclusion }}",
                "fields": [
                  {
                    "title": "Service",
                    "value": "${{ steps.service-name.outputs.service_name }}",
                    "short": true
                  },
                  {
                    "title": "Status",
                    "value": "${{ github.event.workflow_run.conclusion }}",
                    "short": true
                  },
                  {
                    "title": "Commit",
                    "value": "${{ github.event.workflow_run.head_commit.id }}",
                    "short": true
                  },
                  {
                    "title": "Author",
                    "value": "${{ github.event.workflow_run.head_commit.author.name }}",
                    "short": true
                  },
                  {
                    "title": "Message",
                    "value": "${{ github.event.workflow_run.head_commit.message }}",
                    "short": false
                  }
                ]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
