AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Template for Campaign Management

Resources:
  CampaignFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      CodeUri: .
      Environment:
        Variables:
          TABLE_NAME: !Ref CampaignTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CampaignTable
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
              Resource: arn:aws:s3:::email-sender-excel/*
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: arn:aws:s3:::email-sender-excel
      Events:
        CampaignApi:
          Type: Api
          Properties:
            Path: /campaigns
            Method: post

  CampaignTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: campaign
      AttributeDefinitions:
        - AttributeName: campaign_id
          AttributeType: S
      KeySchema:
        - AttributeName: campaign_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  CampaignApiUrl:
    Description: "API Gateway endpoint URL for Campaign Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/campaigns"
